spring:
  application:
    name: news-service
  datasource:
    url: ${NEWS_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000           # 커넥션 요청 대기 최대 시간 (ms)
      idle-timeout: 30000                 # 사용되지 않는 커넥션 회수 시간 (ms)
      max-lifetime: 60000                 # 커넥션 최대 생존 시간 (ms)
      leak-detection-threshold: 2000      # 누수 추적 기준 시간 (ms)
  jpa:
    hibernate:
      ddl-auto: update
      use-sql-comments: true
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

gateway:
  url: http://localhost:8080

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 3000
        readTimeout: 5000

server:
  port: 8082
  address: 0.0.0.0
