spring:
  application:
    name: news-service
  datasource:
    url: ${NEWS_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10       # 최대 커넥션 수 제한
      minimum-idle: 1             # 최소 유휴 커넥션 수
      idle-timeout: 30000         # 30초 이상 유휴 상태면 커넥션 반환 (ms)
      max-lifetime: 900000        # 5분 지나면 커넥션 교체 (ms)
      connection-timeout: 5000    # 5초 내에 커넥션 못 얻으면 예외 (ms)
  jpa:
    hibernate:
      ddl-auto: none
      use-sql-comments: true
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
  kafka:
    consumer:
      group-id: news-group
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      auto-offset-reset: earliest

gateway:
  url: http://localhost:8080

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 3000
        readTimeout: 5000

server:
  port: 8082
  address: 0.0.0.0
